language: python
cache: pip
python:
  - "2.7"
env:
  - TOXENV=py27
  - TOXENV=flake8
before_install:
  - pip install coveralls
install:
  - pip install tox
script:
  - tox
after_success:
  - coveralls